name: Run Docker Container

on:
  pull_request:
    types:
      - closed
      
      
jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Docker
        run: |
         docker login --username=mugumbyabenon --password=${{ secrets.DOCKERPASSWORD }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mugumbyabenon/codeplay-flask-api:latest  
      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
             docker rmi -f $(docker images -aq)
             docker pull mugumbyabenon/codeplay-flask-api
             docker stop $(docker ps -a -q)
             docker run --restart=always -d -p 80:5000 mugumbyabenon/codeplay-flask-api

     
